In [1]:
2+3

5

In [2]:
employees=[
    {"name":"John","salary":5000},
    {"name":"Ada","salary":6000},
    {"name":"Bob","salary":7000},
]
total_salary=sum(emp["salary"] for emp in employees)
average_salary=total_salary/len(employees)
print("Employee Details")
for emp in employees:
    print(f"Name:{emp['name']}")
    print(f"Total Salary:{total_salary} is total salary of all")
    print(f"{average_salary} is average salary of all")

Employee Details
Name:John
Total Salary:18000 is total salary of all
6000.0 is average salary of all
Name:Ada
Total Salary:18000 is total salary of all
6000.0 is average salary of all
Name:Bob
Total Salary:18000 is total salary of all
6000.0 is average salary of all


In [4]:
n = 10
num1 = 0
num2 = 1
next_number = num2
count = 1
while count <= n:
    print(next_number,end=" ")
    count += 1
    num1,num2 = num2,next_number
    next_number = num1 + num2
    print()

1 
2 
3 
5 
8 
13 
21 
34 
55 
89 


In [7]:
def Fibonacci(n):
    if n<0:
     print("Incorrect input")
    elif n == 0:
     return 0
    elif n == 1 or n == 2:
     return 1
    else:
     return Fibonacci(n-1) + Fibonacci(n-2)
print(Fibonacci(9))

34


In [9]:
import numpy as np
from scipy import linalg
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])
matrix_sum = matrix1 + matrix2
matrix_product = np.dot(matrix1, matrix2)
print("Matrix Sum:\n", matrix_sum)
print("Matrix Product:\n", matrix_product)
A = np.array({[3, 1], [1, 2]})
B = np.array([9, 8])
solution = linalg.solve(A, B)
print("Solution to Ax = B:",solution)

Matrix Sum:
 [[ 6  8]
 [10 12]]
Matrix Product:
 [[19 22]
 [43 50]]


TypeError: unhashable type: 'list'

In [14]:
import numpy as np
from scipy import linalg
# Define two matrices
matrix1 = np.array([[1, 2],[3, 4]])
matrix2 = np.array([[5, 6],[7, 8]])
# matrix operations
matrix_sum = matrix1 + matrix2
matrix_product = np.dot(matrix1, matrix2)
print("Matrix sum:\n", matrix_sum)
print("Matrix Product:\n", matrix_product)
# solve a system of linear equations: Ax = B
A = np.array([[3, 1], [1, 2]])
B = np.array([9, 8])
solution = linalg.solve(A, B)
print("Solution to Ax = B:",solution)

Matrix sum:
 [[ 6  8]
 [10 12]]
Matrix Product:
 [[19 22]
 [43 50]]
Solution to Ax = B: [2. 3.]


In [ ]:
#Python code to demonstrate the working of mean(), median(), mode()
# importing statistics to handle statistical operations
from statistics import mean
from statistics import mode
from statistics import median
from statistics import median_low
from statistics import median_high
from statistics import median_high
from statistics import variance
from statistics import stdev
#List of positive integer numbers
data1 = [20, 30, 40, 20, 50, 50, 70, 90, 50, 10]
#List of floating point values